### ISSUE TITLE
File name interception problem after decompression

### ISSUE THREAD

**Issue by qclucky7** [mmadfox/go-crx3#1]
After I decompress the file name will be intercepted more。
Originally from golang strings.TrimRight()

```
println(strings.TrimRight("CaptainBIapp.zip", ".zip")) //CaptainBIa
```

Because I need the unzipped file name, but the api return value is not provided. The file name was intercepted in the previous step, which caused the file name to not match, and the file could not be read.

**Comment by GravityMatrix** [comment]
```
println(strings.TrimSuffix("CaptainBIapp.zip", ".zip")) //CaptainBIapp
```
is right

**Comment by mmadfox** [comment]
Hello, I was in a different context and apologize for the delayed response. I will fix it soon.
