### ISSUE TITLE
Extend `keygen` command to support RSA-3072 and RSA-4096

### ISSUE THREAD

**Issue by przemoc** [mmadfox/go-crx3#6]
Right now in `crx3` new private keys are hardcoded to be RSA-2048. I haven't investigated current support for RSA-3072 and RSA-4096 in CRX in Google Chrome (or Microsoft Edge), but at least per [CRX₃ Design Doc](https://docs.google.com/document/d/1pAVB4y5EBhqufLshWMcvbQ5velk0yMGl5ynqiorTCG4/preview) they intended to use bigger keys, RSA-4096 specifically, so it would be good to support them (and ideally switch to at least RSA-3072 by default).

**Comment by mmadfox** [comment]
Thank you for the information! I have been in a different context for a while and haven’t been following the updates on crx3. I will study the subject in detail soon and make adjustments to the tool.

**Comment by mmadfox** [comment]
Thank you for the information! I have been in a different context for a while and haven’t been following the updates on crx3. I will study the subject in detail soon and make adjustments to the tool.

**Comment by mmadfox** [comment]
In the new release, I made adjustments to the key size.
