### ISSUE TITLE
Support for buffered pack

### ISSUE THREAD

**Issue by leetrout** [mmadfox/go-crx3#7]
@mmadfox Would you be open to a PR to add support for packing in memory instead of the filesystem?

I'd like to have something like:

```go
var b bytes.Buffer
if err := crx3.Extension("/path/to/extension").PackToBuf(b); err != nil {
	panic(err)
}
b.WriteTo(someHTTPResponseWriter)
```

**Comment by mmadfox** [comment]
Yes, this is a very good suggestion. 

It seems to me this is more idiomatic than passing a Buffer. What do you think?
```go
var b bytes.Buffer
if err := crx3.Extension("/path/to/extension").WriteTo(b); err != nil {
	panic(err)
}
b.WriteTo(someHTTPResponseWriter)
```

**Comment by mmadfox** [comment]
Added API for packing into a buffer. See the [example](https://github.com/mmadfox/go-crx3/tree/master/examples/pack_to_memory)

**Comment by leetrout** [comment]
Oh thank you very much!
